### ISSUE TITLE
Can I provide my `.cljstyle` configuration?

### ISSUE THREAD

**Issue by alexdao3** [0918nobita/setup-cljstyle#235]
Hi there, thanks for this GH action!

Is there a convenient way to provide a custom `.cljstyle` file? Currently `cljstyle` seems to get invoked with a default configuration.

My custom `.cljstyle` file provided below just in case:

```
{:rules {:indentation {:indents {#"rum\/defc" [[:inner 0]]}}
         :namespaces {:break-libs? false}}}
```

If this isn't currently supported, and you can point me roughly to what needs to be done to enable this behavior, I'd be interested in contributing. Thanks!

**Comment by 0918nobita** [comment]
Thank you for suggesting this new feature.

After careful consideration, I decided not to provide the ability to specify configuration files in this action, because cljstyle doesn't have the ability to specify paths of configuration files to load directly on the command line.

If you want to apply custom configurations, it is recommended that you add `.cljstyle` file to the root (or sub) directory of your clojure project and manage it with Git.
